[package]
name = "day07"
version = "0.1.0"
authors = ["Stef B <regendo@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
day05 = { path = "../day05" }
